import { HeaderLayout } from "@/layouts/header-layout";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";

import type { Metadata } from "next";

import "../../public/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): JSX.Element {
	return (
		<html lang="en">
			<body
				className={cn(
					inter.className,
					"bg-[size:24px_24px]",
					"bg-zinc-900 text-base-text antialiased py-8",
					"bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)]",
				)}
			>
				<HeaderLayout />
				{children}
			</body>
		</html>
	);
}
